### ISSUE TITLE
5% perf degradation in ROCm OpenCL 2.3 vs. 2.2

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#766]
Using GpuOwl https://github.com/preda/gpuowl
Ubuntu 19.04, Linux kernel 5.0.7, Radeon VII

Upon upgrade ROCm 2.2 -> 2.3, without changing anything else, there is a performance degradation of 5-6% in GpuOwl.

Upon seeing this I tried to move back to ROCm 2.2, but it seems 2.2 is missing from the archive
http://repo.radeon.com/rocm/archive/ , so I downgraded to ROCm 2.1.

For comparison I attach isa dump with "old" (ROCm 2.1) and "new" (ROCm 2.3), where new is 5% slower.

Also please provide a way to install back ROCm 2.2 (e.g. by uploading it to archive).

[new.txt](https://github.com/RadeonOpenCompute/ROCm/files/3077435/new.txt)
[old.txt](https://github.com/RadeonOpenCompute/ROCm/files/3077436/old.txt)

**Comment by preda** [comment]
If desired I can provide running instructions for GpuOwl for repro.

**Comment by preda** [comment]
I have a manual ROCm OpenCL build, with the manifest below, that I synced and built now and it also displays the performance degradation.

/rocm-opencl$ repo info
Manifest branch: master
Manifest merge branch: refs/heads/master
Manifest groups: all,-notdefault
----------------------------
Project: ROCm-OpenCL-Runtime
Mount path: /home/preda/rocm-opencl/opencl
Current revision: master
Local Branches: 2 [amd-master, master]
----------------------------
Project: OpenCL-ICD-Loader
Mount path: /home/preda/rocm-opencl/opencl/api/opencl/khronos/icd
Current revision: master
Local Branches: 0
----------------------------
Project: ROCm-OpenCL-Driver
Mount path: /home/preda/rocm-opencl/opencl/compiler/driver
Current revision: master
Local Branches: 1 [master]
----------------------------
Project: llvm
Mount path: /home/preda/rocm-opencl/opencl/compiler/llvm
Current revision: amd-common
Local Branches: 1 [amd-common]
----------------------------
Project: clang
Mount path: /home/preda/rocm-opencl/opencl/compiler/llvm/tools/clang
Current revision: amd-common
Local Branches: 1 [amd-common]
----------------------------
Project: lld
Mount path: /home/preda/rocm-opencl/opencl/compiler/llvm/tools/lld
Current revision: amd-common
Local Branches: 1 [amd-common]
----------------------------
Project: ROCm-Device-Libs
Mount path: /home/preda/rocm-opencl/opencl/library/amdgcn
Current revision: master
Local Branches: 1 [master]
----------------------------

**Comment by preda** [comment]
I have a manual ROCm OpenCL build, with the manifest below, that I synced and built now and it also displays the performance degradation.

/rocm-opencl$ repo info
Manifest branch: master
Manifest merge branch: refs/heads/master
Manifest groups: all,-notdefault
----------------------------
Project: ROCm-OpenCL-Runtime
Mount path: /home/preda/rocm-opencl/opencl
Current revision: master
Local Branches: 2 [amd-master, master]
----------------------------
Project: OpenCL-ICD-Loader
Mount path: /home/preda/rocm-opencl/opencl/api/opencl/khronos/icd
Current revision: master
Local Branches: 0
----------------------------
Project: ROCm-OpenCL-Driver
Mount path: /home/preda/rocm-opencl/opencl/compiler/driver
Current revision: master
Local Branches: 1 [master]
----------------------------
Project: llvm
Mount path: /home/preda/rocm-opencl/opencl/compiler/llvm
Current revision: amd-common
Local Branches: 1 [amd-common]
----------------------------
Project: clang
Mount path: /home/preda/rocm-opencl/opencl/compiler/llvm/tools/clang
Current revision: amd-common
Local Branches: 1 [amd-common]
----------------------------
Project: lld
Mount path: /home/preda/rocm-opencl/opencl/compiler/llvm/tools/lld
Current revision: amd-common
Local Branches: 1 [amd-common]
----------------------------
Project: ROCm-Device-Libs
Mount path: /home/preda/rocm-opencl/opencl/library/amdgcn
Current revision: master
Local Branches: 1 [master]
----------------------------

**Comment by aaksud** [comment]
Hi the apt,yum tar balls for ROCm 2.2 are available now under: http://repo.radeon.com/rocm/archive/
You can also access them: http://repo.radeon.com/rocm/yum/2.2/ , http://repo.radeon.com/rocm/apt/2.2/

**Comment by sshaik123** [comment]
Preda, 

Can you please provide the instructions on how to build.  We are seeing errors while building the master branch code.  please find the make log in the attachment.

[build,log.txt](https://github.com/RadeonOpenCompute/ROCm/files/3085061/build.log.txt)

**Comment by preda** [comment]
@sshaik123 : I looked at the compilation errors, it seems that the compiler is not supporting c++ 17. Could you please try a more recent compiler? I know it works for sure with g++ 8 and g++ 9. What version is the compiler you used? (g++ --version)

Other than that, everything seems fine, so just use a newer compiler and it should work.

**Comment by preda** [comment]
@sshaik123 after compilation, running is easy, e.g.:
./gpuowl -prp 84682337
And it will display timing information.
./gpuowl -h for other command line options, such as -device N to select a specific GPU.

**Comment by sshaik123** [comment]
@preda, Thanks . Now we are able to build using latest gcc.  we are working on verifying the drop from 2.2 to 2.3 on our setups.
I think it takes more time to run with test -prp value 84682337.  Can we use the lower value to repro the perf drop issue. Please confirm.

**Comment by preda** [comment]
@sshaik123 You don't have to run the *whole* PRP test -- timing information is displayed for every 10K iterations, in the form "1.02 ms/sq", millis per squaring. Just keep it running for about 10 or 20 lines to be displayed (i.e. 1M or 2M iterations), which should be in the order of 1 or 2 minutes.

Also, during the test, please watch for the GPU to not thermal throttle. Normally I set the sclock manually to something lower than max, e.g. on Radeon VII I use rocm-smi --setsclk 4.

Normally the timing information should be pretty stable (very low variance) between iterations, once the GPU reaches the stable temperature.

**Comment by preda** [comment]
@sshaik123 The "-time" option can be useful to pin down the origin of the performance difference. "-time" will display timing information per kernel. (it does have an overhead, but it gives an overall idea of where the time is spent). I'd expect the analysis to likely show that there is one slow kernel.

**Comment by preda** [comment]
> I think it takes more time to run with test -prp value 84682337. Can we use the lower value to repro the perf drop issue. Please confirm.
To answer the question: the value passed to -prp ("the exponent") must be similar (close) to the one in the example in order to use the right FFT setup, and repro (the FFT size is displayed at startup). A much lower exponent changes the FFT size, which changes the whole problem.

**Comment by sshaik123** [comment]
@preda, Thanks for the info. I'm able to repro the issue. on my setup I m getting a drop of ~4.5 % from 2.2 to 2.3 . we are working on investing the root cause.

**Comment by sshaik123** [comment]
Update: Internal ticket has been filed . Issue has been root caused ,  we are working on the fix.

**Comment by preda** [comment]
Has this been fixed in ROCm 2.4?

**Comment by preda** [comment]
Here is some diagnosis:
In the generated ISA, for the kernel "transposeW", ROCm 2.2 generates 117 vGPRs, while ROCm 2.4 generates 129 vGPRs. This produces a significant slow-down in this kernel.

Now the bug is: if ROCm 2.2 can compile that kernel with only 117 vGPRs, why ROCm 2.4 can't do the same, and instead goes for 129 vGPRs which is such a bad number, halving the occupancy and producin an obvious slowdown.

**Comment by preda** [comment]
In a recent commit in gpuowl
https://github.com/preda/gpuowl/commit/9b66d3fe6cc041a3dd873800f74d664b03ee020f
I re-structured my code in the affected kernel to get the compiler to not jump over 128vGPRs, and my thus my problem is fixed (by finding a work-around).

**Comment by preda** [comment]
Closing as old.
