### ISSUE TITLE
Errors installing on kernel 4.17 or 4.18

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#473]
When attempting ROCm 1.8.2 install on Ubuntu 18.04 with kernel 4.17 or 4.18 (tried both), these are the errors:
Building initial module for 4.18.0-041800rc6-generic
ERROR (dkms apport): kernel package linux-headers-4.18.0-041800rc6-generic is not supported
Error! Bad return status for module build on kernel: 4.18.0-041800rc6-generic (x86_64)
Consult /var/lib/dkms/amdgpu/1.8-192/build/make.log for more information.

/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_drv.c: In function ‘amdgpu_pmops_runtime_suspend’:
/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_drv.c:727:2: error: implicit declaration of function ‘vga_switcheroo_set_dynamic_switch’; did you mean ‘vga_switcheroo_process_delayed_switch’? [-Werror=implicit-function-declaration]
  vga_switcheroo_set_dynamic_switch(pdev, VGA_SWITCHEROO_OFF);

**Comment by preda** [comment]
Good news, it installs and works on Ubuntu 18.04 with kernel 4.15.
Good news too, in one situation I observe a 9% performance increase compared with amdgpu-pro 18.20 in similar setup.

Looking forward to being able to use ROCm with kernel 4.17.

**Comment by mdPlusPlus** [comment]
Afaik the next supported kernel will be 4.19, but I could be wrong.

**Comment by PsySc0rpi0n** [comment]
Same or very similar errors here on Debian 9. Tried kernel 4.9.0-7 and 4.17.0-0.bpo.1-amd64.
I'm not sure the last official kernel supported but if it was 4.15 and the next one is 4.19, it's a pretty nice time gap!

**Comment by PsySc0rpi0n** [comment]
Is there a way to be noticed when the next kernel version is compatible with ROCm?

**Comment by valeriob01** [comment]
Installed ubuntu 18.04 and ROCm and rocm-opencl-dev, but opencl does not work, when running the program it terminates with this error: platform not found .

**Comment by Dekken** [comment]
the function ```vga_switcheroo_set_dynamic_switch``` 

does not exist in kernel 4.17

**Comment by rumatadest** [comment]
Same issue with vga_switcheroo_set_dynamic_switch on Fedora 28. 
tested with lastest standard fedora kernel :  kernel-4.18.5-200.fc28.x86_64 
and drivers rocm-dkms-1.8.199-Linux.rpm

**Comment by mdPlusPlus** [comment]
The original issue should be resolved with the now released ROCm 1.9. I guess this can be closed.

**Comment by ernestoriv7** [comment]
@rumatadest 

Could you please let me know the steps that you followed to installed rocm in fedora 28? I'm planning to use that distro due to hardware compatibility.

**Comment by rumatadest** [comment]
I used "Net install" version Fedora 28.  Fedora-Server-netinst-x86_64-28-1.1.iso
1. Standatd instalation with minumum componets. Only base system and "developmet tools". Without GUI
2. Update to lastest package with yum update.  It will install kernel 4.18.x instead 4.16
3. Next steps from this wiki : https://github.com/RadeonOpenCompute/ROCm#centosrhel-7-both-74-and-75-support
i think that devtoolset-7 is not needed. fedora 28 used gcc 8 from box.
4. add ROCm rpm repo
5. try to install rocm-dkms
6. instalation fail (((

**Comment by ernestoriv7** [comment]
> I used "Net install" version Fedora 28. Fedora-Server-netinst-x86_64-28-1.1.iso
> 
> 1. Standatd instalation with minumum componets. Only base system and "developmet tools". Without GUI
> 2. Update to lastest package with yum update.  It will install kernel 4.18.x instead 4.16
> 3. Next steps from this wiki : https://github.com/RadeonOpenCompute/ROCm#centosrhel-7-both-74-and-75-support
>    i think that devtoolset-7 is not needed. fedora 28 used gcc 8 from box.
> 4. add ROCm rpm repo
> 5. try to install rocm-dkms
> 6. instalation fail (((

Great, thanks. From what I see the ROCm github installation instructions, rocm-dkms is not needed for newer kernels, only the other packages. You can check the details over here.

https://github.com/RadeonOpenCompute/ROCm

Also this link shows the packages that should be installed to install rocm withoud dkms.

https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/1047471-amd-rocm-1-9-available-with-vega-20-support-plus-upstream-kernel-compatibility/page2

I will try to do that on fedora 28 and let you know.

Thanks again

**Comment by preda** [comment]
Closing because ROCm 2.0 can now be installed both on Ubuntu 18.04 and 18.10.

**Comment by jlgreathouse** [comment]
@preda it looks like you and I are both combing through old issues. I was just about to post here. :) Thanks for going through these old issues and cleaning up the solved ones.

If y'all are interested in installing ROCm 1.9.2 or 2.0 (and future versions) on Ubuntu 18.10, Fedora 28, Fedora 29, etc. that using new kernels such as 4.17 or 4.18, you might want to check out our new [Experimental ROC](https://github.com/RadeonOpenCompute/Experimental_ROC) project. This includes scripts that will install ROCm on these systems for you. preda is already aware of these, but I'm putting the link here in case someone else finds this issue through an internet search.

In addition, we have written new documentation to describe the tradeoffs between our `rock-dkms` module and the upstream kernel driver in 4.17 and above. See [this section](https://github.com/RadeonOpenCompute/ROCm/blob/roc-2.0.0/README.md#rocm-support-in-upstream-linux-kernels) for more information and [this section](https://github.com/RadeonOpenCompute/ROCm/blob/roc-2.0.0/README.md#using-debian-based-rocm-with-upstream-kernel-drivers) for some more information about installing using an upstream kernel.

**Comment by Randall-Coding** [comment]
I'm getting this error on Ubuntu 18.04, kernel 4.15, but the other user said 4.15 should work?  

` error: implicit declaration of function ‘vga_switcheroo_set_dynamic_switch’; did you mean ‘vga_switcheroo_process_delayed_switch’`

**Comment by ROCmSupport** [comment]
Hi @Randall-Coding 
4.15 kernel is very old, recommend to use 5.4 or bigger one.
Thank you.
