### ISSUE TITLE
ROCm 1.8.2 broken on Ubuntu 16.04 LTS and 18.04 LTS with kernel 4.15.0-33-generic

### ISSUE THREAD

**Issue by evgeniyosipov** [RadeonOpenCompute/ROCm#510]
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/rock-dkms.0.crash'
Error! Bad return status for module build on kernel: 4.15.0-33-generic (x86_64)
Consult /var/lib/dkms/amdgpu/1.8-192/build/make.log for more information.

Vega 64 LC

**Comment by evgeniyosipov** [comment]
```
ProblemType: Package
DKMSBuildLog:
 DKMS make.log for amdgpu-1.8-192 for kernel 4.15.0-33-generic (x86_64)
 Чт авг 23 19:14:23 MSK 2018
 make: Entering directory '/usr/src/linux-headers-4.15.0-33-generic'
 Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_drm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_module.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/main.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_device.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/lib/chash.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/scheduler/gpu_scheduler.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_memory.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_drv.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_tt.o
   LD [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/lib/amdchash.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_bo.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_chardev.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/symbols.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_topology.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_fence.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_bo_util.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_device.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/scheduler/sched_fence.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_bo_vm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_fence_array.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_pasid.o
   LD [M]  /var/lib/dkms/amdgpu/1.8-192/build/scheduler/amd-sched.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_module.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_object.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_kthread.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_kms.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_lock.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_doorbell.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_io.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_execbuf_util.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_page_alloc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_mn.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_reservation.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_bo_manager.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_flat_memory.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_drm_global.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_page_alloc_dma.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atombios.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/atombios_crtc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_bitmap.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_process.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_pci.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_queue.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_agp_backend.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_connectors.o
   LD [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/amdkcl.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/atom.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_mqd_manager.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_fence.o
   LD [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/amdttm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ttm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_object.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_gart.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_encoders.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_mqd_manager_cik.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_display.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_i2c.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_mqd_manager_vi.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_fb.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_mqd_manager_v9.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_gem.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ring.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_cs.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_bios.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_benchmark.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_kernel_queue.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_test.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_kernel_queue_cik.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_pm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/atombios_dp.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_kernel_queue_vi.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_afmt.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_kernel_queue_v9.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_trace_points.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/atombios_encoders.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_sa.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_packet_manager.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_process_queue_manager.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/atombios_i2c.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_prime.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_device_queue_manager.o
 /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_sa.c: In function ‘amdgpu_sa_bo_dump_debug_info’:
 /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_sa.c:432:52: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘u64 {aka long long unsigned int}’ [-Wformat=]
     seq_printf(m, " protected by 0x%08x on context %d",
                                                    ~^
                                                    %lld
       i->fence->seqno, i->fence->context);
                        ~~~~~~~~~~~~~~~~~             
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_device_queue_manager_cik.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_vm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_device_queue_manager_vi.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ib.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_pll.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_device_queue_manager_v9.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ucode.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_interrupt.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_events.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/cik_event_interrupt.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_bo_list.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_int_process_v9.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ctx.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_dbgdev.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_sync.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_dbgmgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_gtt_mgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_crat.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_vram_mgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_virt.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_rdma.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atomfirmware.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_peerdirect.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_queue_mgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_vf_error.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_sched.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_ipc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_sem.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_amdkfd_fence.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_iommu.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_debugfs.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_debugfs.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ids.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/cik.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/cik_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/kv_smc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/kv_dpm.o
   LD [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/amdkfd.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/ci_smc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/ci_dpm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/dce_v8_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gfx_v7_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/cik_sdma.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/uvd_v4_2.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vce_v2_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/si.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gmc_v6_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gfx_v6_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/si_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/si_dma.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/dce_v6_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/si_dpm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/si_smc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vi.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/mxgpu_vi.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/nbio_v6_1.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/soc15.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/emu_soc.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/mxgpu_ai.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/nbio_v7_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vega10_reg_init.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gmc_v7_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gmc_v8_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gfxhub_v1_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/mmhub_v1_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gmc_v9_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_irq.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/iceland_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/tonga_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/cz_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vega10_ih.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_psp.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/psp_v10_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/psp_v3_1.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_powerplay.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_dpm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/dce_v10_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/dce_v11_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/dce_virtual.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_gfx.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gfx_v8_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/gfx_v9_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/sdma_v2_4.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/sdma_v3_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/sdma_v4_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_uvd.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/uvd_v5_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/uvd_v6_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/uvd_v7_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_vce.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vce_v3_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vce_v4_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_vcn.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/vcn_v1_0.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_amdkfd.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_amdkfd_gfx_v7.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_amdkfd_gfx_v8.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_amdkfd_gfx_v9.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_amdkfd_gpuvm.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_cgs.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_job.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_acp.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/../acp/acp_hw.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_ioc32.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_acpi.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_mn.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/../powerplay/smumgr/smumgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/../powerplay/smumgr/cz_smumgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/../powerplay/smumgr/tonga_smumgr.o
 /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.c:577:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   .get_client_id = amdgpu_atpx_get_client_id,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.c:577:19: note: (near initialization for ‘amdgpu_atpx_handler.get_client_id’)
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/../powerplay/smumgr/fiji_smumgr.o
   CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/../powerplay/smumgr/polaris10_smumgr.o
 cc1: some warnings being treated as errors
 scripts/Makefile.build:332: recipe for target '/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.o' failed
 make[2]: *** [/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.o] Error 1
 make[2]: *** Waiting for unfinished jobs....
 scripts/Makefile.build:606: recipe for target '/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu' failed
 make[1]: *** [/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu] Error 2
 Makefile:1552: recipe for target '_module_/var/lib/dkms/amdgpu/1.8-192/build' failed
 make: *** [_module_/var/lib/dkms/amdgpu/1.8-192/build] Error 2
 make: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
DKMSKernelVersion: 4.15.0-33-generic
Date: Thu Aug 23 19:14:41 2018
DuplicateSignature: dkms:rock-dkms:1.8-192:/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.c:577:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
Package: rock-dkms 1.8-192
PackageVersion: 1.8-192
SourcePackage: rock-dkms
Title: rock-dkms 1.8-192: amdgpu kernel module failed to build

```

**Comment by jlgreathouse** [comment]
Could you please include the following information:

- What distribution you are using
- What version of that distribution
- What packages you've installed before attempting to install this
- What commands you used to allow us to recreate the problem
- What compiler version you are using

**Comment by evgeniyosipov** [comment]
Kubuntu 18.04.1 amd64
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
Installed only stable updates (not pre-release updates)
`sudo apt update && sudo apt dist-upgrade
`
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-16ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)
```

**Comment by jlgreathouse** [comment]
Thank you, I can confirm that I can recreate the problem. I can also confirm that it happens on Ubuntu 16.04 with 4.15.0-33. I believe we've found the problem, I'll try to keep you updated as we make progress on this.

**Comment by preda** [comment]
Same with Ubuntu 18.04 kernel 4.15.0-33

**Comment by boberfly** [comment]
It seemed to compile for me on 4.15.0-30 I believe, but I am having issues with Radeon Pro Render: https://github.com/RadeonOpenCompute/ROCm/issues/503

Cheers

**Comment by jlgreathouse** [comment]
The issue is caused by a patch backported into the -33 kernel. We have identified the problem and are working through process of releasing a hotfix.

**Comment by fangq** [comment]
The last version of rocm I installed was [1.7.1 beta3](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/43#issuecomment-368660609) posted by @gstoner, it worked fine on my Vega64 GPU and Ubuntu 16.04 with a 4.13 kernel. 

I just upgraded rocm to 1.8.192, and the kernel is also upgraded to 4.15.0-33, but rocm stops working. dmesg | grep kfd returns

```
[    1.108303] kfd kfd: Initialized module
[    3.048527] amdgpu 0000:03:00.0: kfd not supported on this ASIC
```

clinfo returns 0 platform and rocminfo returns

`hsa api call failure at line 900, file: /rocmdata/jedwards/git/compute/rocrinfo/rocminfo.cc. Call returned 4104
`
I do not see the error dump as reported by other users (/var/crash/rock-dkms.0.crash), but something isn't working.

let me know if there is a workaround.

**Comment by jlgreathouse** [comment]
ROCm 1.8.2 does not work with Ubuntu running Linux kernel 4.15.0-33. The workaround (until we can finish validating our patch) is to downgrade to downgrade the Linux kernel to 4.15.0-32 or below. For instance, `sudo apt install linux-image-4.15.0-32-generic` and choosing to boot into that from GRUB.

**Comment by fangq** [comment]
I just tried several older kernels (4.15.0-32 and 4.13.0-38), but strangely, I was getting the same empty clinfo output and hsa api call failure error for rocminfo as I got for the -33 kernel. The "kfd not supported on this ASIC" disappeared for the older kernels (perhaps because I removed the amdgpu drivers?).

I did remove/purge the amdgpu kernel and saw rock-dkms rebuilt the kernel  - it only gave the crash message when compiling the -33 kernel, but other older kernels were compiled smoothly. but once I reboot, and verified the kernel version wasn't the -33 kernel, I still could not get rocm 1.8 to run. 

any other things I can look into or provide? thanks

**Comment by fangq** [comment]
by the way, is there an older version rocm (say, 1.8.1) that I can try? deb packages are preferred. thanks

**Comment by jlgreathouse** [comment]
Older versions are also likely to fail for 4.15.0-33; the problem is a compilation error for amdgpu that will be sensitized by the -33 release; older ROCk driver releases will also have this.

If you purge (and maybe removeall) rock-dkms, then boot into your e.g. -32 kernel, and install rock-dkms -- it should properly build the DKMS modules. It might not properly build your initramfs, so after you reboot into -32, try `sudo update-initramfs -u -k all` and reboot again.

**Comment by jlgreathouse** [comment]
We have released ROCm 1.8.3 which should fix this compatibility issue with 4.15.0-33.

**Comment by fangq** [comment]
confirm the new 1.8.199 release fixed the issue on 4.15.0-33. thanks
